### ISSUE TITLE
Suggest to add handling for on websocket connection disconnected

### ISSUE THREAD

**Issue by chavalit** [thomsonreuters/websocket-api#12]
In https://github.com/Refinitiv/websocket-api/blob/master/Applications/Examples/EDP/java/MarketPriceEdpGwAuthentication.java

When the consumer WebSocket connection to ERT in Cloud gets disconnected by the ERT in Cloud, the sample application does not print out any information on the output and the process to refresh the token is still repeating.
So it is quite confusing.
Suggest to impletement [onDisconnected](https://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocketListener.html#onDisconnected-com.neovisionaries.ws.client.WebSocket-com.neovisionaries.ws.client.WebSocketFrame-com.neovisionaries.ws.client.WebSocketFrame-boolean-)() and just terminate the app.
Or even better, re-do the whole authentication and item request again.

**Comment by dmykhailishen** [comment]
@chavalit thank you for reporting the suggestion. Your suggestion will be analyzed and an update about it will be added later on.

**Comment by vlevendel** [comment]
@chavalit This is addressed in RDP Java examples for V2 authentication support. Closing.
