### ISSUE TITLE
Look like a bug in the RDP CSharp Code

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [thomsonreuters/websocket-api#13]
[https://community.developers.refinitiv.com/questions/74765/websocket-api-nul-in-the-response-for-the-rate-req.html](https://community.developers.refinitiv.com/questions/74765/websocket-api-nul-in-the-response-for-the-rate-req.html
)
It looks like to be a bug when adding data to **memoryStream**. 
The value of readBuffer.Count is always 8192 although the retrieved data is smaller than 8192.

**Comment by dmykhailishen** [comment]
@jirapongse-refinitiv, thank you for reporting the issue. This issue will be analyzed and an update about an issue will be added later on.
