### ISSUE TITLE
websocket-client version for RDP Python examples

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [thomsonreuters/websocket-api#14]
The readme.md shows that it requires the websocket-client must be version 0.49 or greater.

However, I am using 0.57.0 and it doesn't work with the market_price_rdpgw_service_discovery.py.

After upgrading to websocket-client 1.1.0, it works fine. Please update the readme.md.

**Comment by dmykhailishen** [comment]
@jirapongse-refinitiv, thank you for reporting the issue. This issue will be analyzed and an update about an issue will be added later on.

**Comment by vlevendel** [comment]
Fixed with tag WSA-1.1.7
