### ISSUE TITLE
Remove / reduce the confusion between username and MachineID

### ISSUE THREAD

**Issue by umernalla** [thomsonreuters/websocket-api#15]
We are still getting customers who are using their username (e.g. corporate email address) for the --user parameter when running the examples - leading to frustration, time waste all around and a very poor introductory experience of Refinitiv.

This is despite Quickstarts, RTO guides and Welcome Emails etc mentioning that MachineID is required for programmatic access to data.

In view of this can we change the README and examples to mention MachineID. Ideally, even show a dummy machineID so that there remains no doubt.
e.g. in code
user = 'GE-A-001234545-1-1234' // Replace with your Machine ID

and on the README page:
<html>
<body>

--user | REQUIRED. MachineID to use when authenticating to Refinitiv Data Platform.
-- | --

</body>
</html>

OR even better change the parameter name to MachineID

**Comment by vlevendel** [comment]
Thank you for bringing this up.  We'll do the needful after confirmation.

**Comment by vlevendel** [comment]
Fixed in documentation.
