### ISSUE TITLE
Redirect from customer support team - case 11082530

### ISSUE THREAD

**Issue by phoboshero** [thomsonreuters/websocket-api#17]
Hi,

We are hitting an authentication issue when trying to integrate FX pricing API from our system, please find details below:
- Account with Refinitiv: Johnny.phan@ebonex.pro
- Get access token via https://api.refinitiv.com:443/auth/oauth2/v1/token: worked
- Calling https://api.refinitiv.com/streaming/pricing/v1/ with access token - error (see error message below)

{
    "error": {
        "id": "1f1bb7bb-52e3-4372-ae55-947cd32d0478",
        "code": "insufficient_scope",
        "message": "access denied. Scopes required to access the resource: [trapi.streaming.pricing.read]. Missing scopes: [trapi.streaming.pricing.read]",
        "status": "Forbidden"
    }
}

We had a call with the customer support team and they can't figure out this issue, please give us a help in an urgent manner since our business is currently blocked by this, thanks a lot.

Best Regards,
Robbin

**Comment by wasin-waeosri** [comment]
Hello @phoboshero 

The "_access denied. Scopes required to access the resource: [trapi.streaming.pricing.read]. Missing scopes: [trapi.streaming.pricing.read]_" error message means the account does not have permission to the Real-Time streaming access and the /streaming/pricing/v1/ endpoint.

Please contact the Account manager to verify the permission.
