### ISSUE TITLE
unable to create rest webservice and retrieve JSON from the below method in websocket 

### ISSUE THREAD

**Issue by ShyamSanghvi** [thomsonreuters/websocket-api#2]
public void onTextMessage(WebSocket websocket, String message) throws JSONException {
                        if(!message.isEmpty()) {
                        	System.out.println("RECEIVED:");

                            JSONArray jsonArray = new JSONArray(message);

                            System.out.println(jsonArray.toString(2));

                            for (int i = 0; i < jsonArray.length(); ++i)
                                processMessage(websocket, jsonArray.getJSONObject(i));
                        }
                    }

**Comment by ShyamSanghvi** [comment]
https://github.com/Refinitiv/websocket-api/blob/master/Applications/Examples/java/MarketPrice.java

this is the link of the method in that class

**Comment by vlevendel** [comment]
@ShyamSanghvi What's the exact error you are noticing?  Also, if connecting to Refinitiv Data Platform, please use examples in Applications/Examples/EDP/java.

**Comment by vlevendel** [comment]
@ShyamSanghvi Are you still experiencing this problem?

**Comment by ShyamSanghvi** [comment]
Hey thanks for the reply
 I got the solution . I was able to put th JSon object into thread and then
retrieve it .
Thanks a ton
Thanks for the concern .sir .

**Comment by vlevendel** [comment]
Thanks for the update.  Closing this issue.
