### ISSUE TITLE
Any plans to update C# projects to .Net 6?

### ISSUE THREAD

**Issue by wasin-waeosri** [thomsonreuters/websocket-api#24]
Hi, 

The [RTSDK C#](https://github.com/Refinitiv/Real-Time-SDK/tree/master/CSharp) is now released with .NET Core 6.0 supported. However, the WebSocket C# projects still use older versions of the frameworks

- WebSocket C# examples support Visual Studio 2015 (.Net framework 4.5.1, no cross-platform)
- WebSocket C# examples support .Net core 3.1 (cross platform)

Do you have any plans to update them to up to dated .Net Core 6?

**Comment by fogol** [comment]
@wasin-waeosri Thank you for this observation.  We have already made this change and intend to publish support after it has been tested.  This is expected to be supported in Q1.

**Comment by vlevendel** [comment]
@wasin-waeosri Addressed with tag WSA-1.1.11.
