### ISSUE TITLE
Go market_price examples gives 403

### ISSUE THREAD

**Issue by RuRu92** [thomsonreuters/websocket-api#27]
Hey all.

I have downloaded bunch of examples as to experiment on connecting to our internal trep servers.

I have tested with Java and Python that those two work fine without any issues. 

However, when I try using golang example, I am getting 403 Forbidden, even tho the same parameters are being used.
I suspect some issues with how gorilla websockets are handling the handshake.

Given that its no longer supported, the examples for go should be updated, to fix the error and use a supported framework.

**Comment by L-Karchevska** [comment]
@RuRu92 Thank you for letting us know about this issue, we will look into it and apply the necessary changes.

**Comment by ayurov2** [comment]
Hi @RuRu92, we've tested this on our end and are not seeing any such errors with the Go websocket examples when connecting to a live Real-Time server endpoint using the latest gorilla websockets version. Was there something you might have been testing- or testing against, that had improper input set in some way? Any additional information you could give us at all for your testing environment and setup that might clue us in to what you might have been doing to reproduce the problem?
 
Thanks much.

**Comment by ayurov2** [comment]
Hi @RuRu92, for now I will close this issue as we have not been able to reproduce this ourselves, however if you are still able to reproduce this consistently, please feel free to open up a new issue with additional details on reproduction steps. We'll be more than happy to continue investigations and help address it. We greatly appreciate that you've run through these examples against your internal servers and reached out in the first place when you noticed an issue.
