### ISSUE TITLE
How to get currency holiday?

### ISSUE THREAD

**Issue by peakzhao** [thomsonreuters/websocket-api#29]

**Comment by fogol** [comment]
@peakzhao Thank you for your question! I believe, you can find the answer on [LSEG Developer Community Portal](https://developers.lseg.com/). Please, take a look at the existing one:

[Currency holidays](https://community.developers.refinitiv.com/questions/56927/currency-holidays.html)

I just tried to change the RIC code in my JSON request to _'US/HOLIDAY'_ and have received the table in the response:

![image](https://github.com/Refinitiv/websocket-api/assets/23211336/f84cb7a4-f742-4909-92c9-3dcd66ee27c7)

I believe, this information is exactly that you were looking for. Sure, you need to parse the table.

Please, do not hesitate to ask other questions on [LSEG Developer Community Portal](https://developers.lseg.com/).

If this answer solved your question, I will close this issue. Thank you!

**Comment by peakzhao** [comment]
@fogol Thanks, I found it before. Can I know the Endpoint? Like https://api.refinitiv.com/streaming/......

**Comment by fogol** [comment]
@peakzhao The endpoint is a part of the Service Discovery process. Please, take a look at RDP Examples, like 

**[Python Refinitiv Data Platform Examples](https://github.com/Refinitiv/websocket-api/tree/master/Applications/Examples/RDP/python)**

You can use one of

market_price_rdpgw_service_discovery
market_price_rdpgw_client_cred_auth
market_price_rdpgw_jwt_auth

Depends on which Authentication type you need.

I have used **[market_price_rdpgw_service_discovery](https://github.com/Refinitiv/websocket-api/blob/master/Applications/Examples/RDP/python/market_price_rdpgw_service_discovery.py)** one, to run my code sample with 'US/HOLIDAY' RIC request.

**Comment by peakzhao** [comment]
@fogol Do you mean than Get holiday data according to web socket? Is there a Rest-API method to obtain holidays? Thanks.

**Comment by vlevendel** [comment]
> @fogol Do you mean than Get holiday data according to web socket? Is there a Rest-API method to obtain holidays? Thanks.

Yes, a websocket connection is needed. In the context of using the sample applications we provide on this site, you must make a websocket connection to a Real-time host and port (incidentally also called 'endpoint') and request the RIC, 'US/HOLIDAY' to get the holiday content you seek. As for which host and port to use, if you are connecting to RDP, you may use another API called "service discovery", to get this (host/port) information.  Please see fogol's explanation above.

**Comment by vlevendel** [comment]
> @fogol Thanks, I found it before. Can I know the Endpoint? Like https://api.refinitiv.com/streaming/......

@peakzhao  Please use the Q&A section on LSEG Developer Community Portal to request access to the Snapshot API (REST API which will permit you to make a request for a RIC like 'US/HOLIDAY').

Closing issue for now.  Please let us know if there are further questions.
