### ISSUE TITLE
Refinitiv organization/company name in Contributor License Agreement?

### ISSUE THREAD

**Issue by apjanke** [thomsonreuters/websocket-api#3]
Hi folks,

In the Contributor License Agreements in this repo, as of 1/7/2020, the "Us" is just described as "Websocket API". That's not a legal entity, is it? And it's not very descriptive – there's a lot of Websocket APIs out there. Shouldn't the "Us" be something like "Refinitiv, Inc., a U.S. corporation incorporated under New York law" or "The Refinitiv Elektron Messaging API Websocket API", and then include some corporate contact info like an address somewhere in the agreement? (I see a URL there, but URLs aren't very permanent or official-like, right?)

**Comment by vlevendel** [comment]
@apjanke We will address the Agreement text with the next GitHub push.  Thank you for bringing this to our attention.

**Comment by apjanke** [comment]
Cool. Do you know when this might happen? I'm ready to submit some PRs as soon as I sign a CLA.

**Comment by vlevendel** [comment]
@apjanke Per Refinitiv legal team, this is Agreement text is per open source community terms and approved.  So, there will be no changes to wording.

**Comment by apjanke** [comment]
Okay. I'll send it in as is.
