### ISSUE TITLE
Streaming example with updates or repeated polling

### ISSUE THREAD

**Issue by apjanke** [thomsonreuters/websocket-api#4]
It seems like it's a bit of a jump to get from the one-shot examples currently in this repo to a connection or session that stays open and either receives streaming data or repeatedly polls for refresh updates. In particular, the authentication token expires after about 5 minutes and requires refreshing. Maybe an example of how to do that could be added?

**Comment by vlevendel** [comment]
@apjanke please see examples in EDP section:  https://github.com/Refinitiv/websocket-api/tree/master/Applications/Examples/EDP

There are typically 2 examples for each of the languages:  authentication (does token management for you) and service discovery (does a look up on which host/port to connect to in a given region and uses that to make a streaming connection and does token management ).

**Comment by apjanke** [comment]
Those are the examples I was looking at. The issue with those is that they just do a single authentication and maybe a single query. For real-world applications that need to stay open and do streaming or repeated polling, some additional work needs to be done, including refreshing the authentication token (probably on a dedicated worker thread), which the examples don't cover. (At work, we just built a feed client on top of these examples, and it took some work and trial-and-error to figure out what needed to be done.) It would have been useful if there was an extended version of these examples that showed how to keep an authorization session going beyond the initial token expiration time.

**Comment by apjanke** [comment]
Oh wait, nevermind: that example *does* include a refresh. It must have just gotten deleted while we were working on the code and transforming it into our own app.

Closing as not a problem.
